packaging_format = 2

id = "minecraft_bedrock"
name = "Minecraft Bedrock Server"
description.en = "Three-dimensional sandbox construction game"

version = "1.21.102.1~ynh1"

[upstream]
license = "GPL-3.0-only"

[install]
    [install.description]
    type = "markdown"
    ask.en = "This package installs a Minecraft Bedrock dedicated server."

    [install.info]
    type = "alert"
    ask.en = "You can configure initial server name, game mode, difficulty, and world seed."

    [install.server_name]
    type = "string"
    default = "Bedrock Server"
    optional = true
    ask.en = "Server name"
    help.en = "Used as the server name. Allowed values: any string without semicolon (;)."
    [install.server_name.pattern]
    regexp = "^[^;]*$"
    error = "Server name cannot contain ';'."

    [install.gamemode]
    type = "select"
    default = "creative"
    optional = true
    ask.en = "Game mode"
    help.en = "Sets the game mode for new players."
    choices = ["survival", "creative", "adventure"]

    [install.difficulty]
    type = "select"
    default = "easy"
    optional = true
    ask.en = "Difficulty"
    help.en = "Sets the world difficulty."
    choices = ["peaceful", "easy", "normal", "hard"]

    [install.level_seed]
    type = "string"
    default = ""
    optional = true
    ask.en = "Level seed"
    help.en = "Seed used to generate the world. Allowed values: any string. Leave empty for random generation."

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = true
ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "500M"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.102.1.zip"
        sha256 = "87dc223a4bbdd15a0cc39d9b3630d4ae50e635898543a087ab8ef97cc0f9432e"
        in_subdir = false
        extract = true

    [resources.ports]
    main.default = 19132
    main.exposed = "UDP"
    main.fixed = false

    [resources.system_user]

    [resources.data_dir]

    [resources.install_dir]

    [resources.permissions]
