packaging_format = 2

id = "minecraft_bedrock"
name = "Minecraft Bedrock Server"
description.en = "Three-dimensional sandbox construction game"

version = "1.21.102.1~ynh1"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = false

disk = "100M"
ram.build = "50M"
ram.runtime = "500M"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.102.1.zip"
        sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        in_subdir = false
        extract = true

    [resources.ports]
    main.default = 19132
    main.exposed = "UDP"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
