#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================

ynh_script_progression --message="Backing up Minecraft data..." --weight=1

ynh_backup --src_path="$install_dir/worlds"

ynh_script_progression --message="Backup completed" --last
