#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================

ynh_print_info "Declaring Minecraft data to be backed up..."

ynh_backup --src_path="$data_dir"
ynh_backup --src_path="$install_dir/server.properties"
ynh_backup --src_path="$install_dir/allowlist.json"
ynh_backup --src_path="$install_dir/permissions.json"
