#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=10

ynh_setup_source --dest_dir="$install_dir" --source_id="main" --keep="worlds"

chmod o+x "$install_dir/bedrock_server"

#=================================================
# DEPLOY APP-MANAGED CONFIG FILES
#=================================================

ynh_add_config --template="server.properties" --destination="$install_dir/server.properties"
ynh_add_config --template="allowlist.json" --destination="$install_dir/allowlist.json"
ynh_add_config --template="permissions.json" --destination="$install_dir/permissions.json"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=2

ynh_add_systemd_config

yunohost service add $app --description="Three-dimensional sandbox construction game" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
