#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================
ynh_script_progression --message="Stopping Minecraft service..." --weight=1 --line_match=".*Stopped minecraft_bedrock.service.*"

ynh_script_progression --message="Backing up Minecraft data..." --weight=1

ynh_backup --src_path="$data_dir"

# Stop the service before removal
ynh_systemd_action --service_name=$app --action=stop --log_path=systemd

ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

ynh_remove_systemd_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
