#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_script_progression --message="Restoring Minecraft data..." --weight=1

ynh_restore --origin_path="$install_dir/worlds"

ynh_script_progression --message="Restore completed" --last
