#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPGRADE STEPS
#=================================================
ynh_script_progression --message="Upgrading Minecraft Bedrock Server..." --weight=1

# Download and setup new source
ynh_script_progression --message="Downloading new version..." --weight=1

ynh_setup_source --dest_dir="$install_dir" --source_id="main" --keep="worlds allowlist.json permissions.json server.properties"

chmod o+x "$install_dir/bedrock_server"

ynh_script_progression --message="Upgrade completed" --last
